# Generated by Django 6.0.3 on 2026-03-17 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HelpMe_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth (YYYY-MM-DD)')),
                ('picture', models.ImageField(default='profilepics/default.png', upload_to='profilepics/', verbose_name='User picture')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Join date')),
                ('password_hint', models.CharField(max_length=100, verbose_name='Password hint')),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('LIMITED', 'Limited'), ('ADMIN', 'Admin')], default='STANDARD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('pollitem_id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
                ('approval_status', models.CharField(choices=[('CREATOR', 'Creator'), ('NEUTRAL', 'Neutral'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='NEUTRAL', max_length=10)),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.comment')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.poll')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SUGGESTION', 'Suggestion')], max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('comment_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.comment')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('pollitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.pollitem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username', 'session_key', 'pollitem_id')},
            },
        ),
    ]
