# Generated by Django 6.0.3 on 2026-03-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('postedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('pollID', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateOfBirth', models.DateField()),
                ('picture', models.ImageField(upload_to='user_pics/')),
                ('joinDate', models.DateField(auto_now_add=True)),
                ('passwordHint', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('STANDARD', 'Standard'), ('LIMITED', 'Limited'), ('ADMIN', 'Admin')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('pollItemID', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=50)),
                ('approvalStatus', models.CharField(choices=[('CREATOR', 'Creator'), ('NEUTRAL', 'Neutral'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='NEUTRAL', max_length=10)),
                ('commentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HelpMe_app.comment')),
                ('pollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.question'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('notificationType', models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('SUGGESTION', 'Suggestion')], max_length=10)),
                ('isRead', models.BooleanField(default=False)),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpMe_app.question')),
            ],
        ),
    ]
