# Generated by Django 6.0.3 on 2026-03-14 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpMe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='questionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HelpMe_app.question'),
        ),
    ]
